// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Sabnzbd.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Sabnzbd.OpenApiClient.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sabnzbd.OpenApiClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api{?archive*,cat*,category*,connections*,del_files*,dir*,enable*,failed_only*,keyword*,last_history_update*,limit*,name*,nzbname*,nzf_ids*,nzo_ids*,output*,password*,pp*,priority*,script*,search*,section*,size*,skip_dashboard*,sort*,sort_cats*,sort_string*,sort_type*,start*,status*,username*,value*,value2*,value3*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sabnzbd.OpenApiClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api{?archive*,cat*,category*,connections*,del_files*,dir*,enable*,failed_only*,keyword*,last_history_update*,limit*,name*,nzbname*,nzf_ids*,nzo_ids*,output*,password*,pp*,priority*,script*,search*,section*,size*,skip_dashboard*,sort*,sort_cats*,sort_string*,sort_type*,start*,status*,username*,value*,value2*,value3*}", rawUrl)
        {
        }
        /// <summary>
        /// Executes the command selected by mode and, where applicable, name. The response shape depends on those values. version and auth do not require an API key.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Sabnzbd.OpenApiClient.Api.ApiRequestBuilder.ApiRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Sabnzbd.OpenApiClient.Api.ApiRequestBuilder.ApiRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponse>(requestInfo, global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Upload an NZB file or retry a job with an additional NZB
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponse?> PostAsync(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponse> PostAsync(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponse>(requestInfo, global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Executes the command selected by mode and, where applicable, name. The response shape depends on those values. version and auth do not require an API key.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sabnzbd.OpenApiClient.Api.ApiRequestBuilder.ApiRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Sabnzbd.OpenApiClient.Api.ApiRequestBuilder.ApiRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, "{+baseurl}/api?mode={mode}{&archive*,cat*,category*,connections*,del_files*,dir*,enable*,failed_only*,keyword*,last_history_update*,limit*,name*,nzbname*,nzf_ids*,nzo_ids*,output*,password*,pp*,priority*,script*,search*,section*,size*,skip_dashboard*,sort*,sort_cats*,sort_string*,sort_type*,start*,status*,username*,value*,value2*,value3*}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Upload an NZB file or retry a job with an additional NZB
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "multipart/form-data", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sabnzbd.OpenApiClient.Api.ApiRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Sabnzbd.OpenApiClient.Api.ApiRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Sabnzbd.OpenApiClient.Api.ApiRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Executes the command selected by mode and, where applicable, name. The response shape depends on those values. version and auth do not require an API key.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ApiRequestBuilderGetQueryParameters 
        {
            /// <summary>Display history (default) or archived items</summary>
            [QueryParameter("archive")]
            public int? Archive { get; set; }
            /// <summary>Only return jobs with the specified category or categories (separated by a comma) Use * for Default</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cat")]
            public string? Cat { get; set; }
#nullable restore
#else
            [QueryParameter("cat")]
            public string Cat { get; set; }
#endif
            /// <summary>Only return jobs with the specified category or categories (separated by a comma) Use * for Default</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("category")]
            public string? Category { get; set; }
#nullable restore
#else
            [QueryParameter("category")]
            public string Category { get; set; }
#endif
            /// <summary>SABnzbd connections query parameter.</summary>
            [QueryParameter("connections")]
            public int? Connections { get; set; }
            /// <summary>SABnzbd del_files query parameter.</summary>
            [QueryParameter("del_files")]
            public int? DelFiles { get; set; }
            /// <summary>SABnzbd dir query parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("dir")]
            public string? Dir { get; set; }
#nullable restore
#else
            [QueryParameter("dir")]
            public string Dir { get; set; }
#endif
            /// <summary>SABnzbd enable query parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("enable")]
            public string? Enable { get; set; }
#nullable restore
#else
            [QueryParameter("enable")]
            public string Enable { get; set; }
#endif
            /// <summary>Only show failed jobs (shorthand for status=Failed)</summary>
            [QueryParameter("failed_only")]
            public int? FailedOnly { get; set; }
            /// <summary>SABnzbd keyword query parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("keyword")]
            public string[]? Keyword { get; set; }
#nullable restore
#else
            [QueryParameter("keyword")]
            public string[] Keyword { get; set; }
#endif
            /// <summary>Only return full output if anything has changed since last_history_update, the last update is given by a previous call to history</summary>
            [QueryParameter("last_history_update")]
            public long? LastHistoryUpdate { get; set; }
            /// <summary>Number of jobs to display</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Command to execute.</summary>
            [QueryParameter("mode")]
            public global::Soenneker.Sabnzbd.OpenApiClient.Models.Mode? Mode { get; set; }
            /// <summary>URL-encoded version of the link to the NZB to be fetched.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name")]
            public string? Name { get; set; }
#nullable restore
#else
            [QueryParameter("name")]
            public string Name { get; set; }
#endif
            /// <summary>Name of the job, if empty the NZB filename is used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("nzbname")]
            public string? Nzbname { get; set; }
#nullable restore
#else
            [QueryParameter("nzbname")]
            public string Nzbname { get; set; }
#endif
            /// <summary>SABnzbd nzf_ids query parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("nzf_ids")]
            public string? NzfIds { get; set; }
#nullable restore
#else
            [QueryParameter("nzf_ids")]
            public string NzfIds { get; set; }
#endif
            /// <summary>Only return jobs with these nzo_ids (separated by a comma)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("nzo_ids")]
            public string? NzoIds { get; set; }
#nullable restore
#else
            [QueryParameter("nzo_ids")]
            public string NzoIds { get; set; }
#endif
            /// <summary>Response format.</summary>
            [QueryParameter("output")]
            public global::Soenneker.Sabnzbd.OpenApiClient.Models.Output? Output { get; set; }
            /// <summary>Password to use when unpacking the job.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("password")]
            public string? Password { get; set; }
#nullable restore
#else
            [QueryParameter("password")]
            public string Password { get; set; }
#endif
            /// <summary>&quot;Post-processing options: -1 = Default (of category) 0 = None 1 = +Repair 2 = +Repair/Unpack 3 = +Repair/Unpack/Delete&quot;</summary>
            [QueryParameter("pp")]
            public int? Pp { get; set; }
            /// <summary>&quot;Priority to be assigned: -100 = Default Priority (of category) -2 = Paused -1 = Low Priority 0 = Normal Priority 1 = High Priority 2 = Force&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("priority")]
            public string? Priority { get; set; }
#nullable restore
#else
            [QueryParameter("priority")]
            public string Priority { get; set; }
#endif
            /// <summary>Script to be assigned, Default will use the script assigned to the category. List of available scripts can be retrieved from get_scripts.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("script")]
            public string? Script { get; set; }
#nullable restore
#else
            [QueryParameter("script")]
            public string Script { get; set; }
#endif
            /// <summary>Filter job names by search term</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search")]
            public string? Search { get; set; }
#nullable restore
#else
            [QueryParameter("search")]
            public string Search { get; set; }
#endif
            /// <summary>SABnzbd section query parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("section")]
            public string? Section { get; set; }
#nullable restore
#else
            [QueryParameter("section")]
            public string Section { get; set; }
#endif
            /// <summary>SABnzbd size query parameter.</summary>
            [QueryParameter("size")]
            public int? Size { get; set; }
            /// <summary>SABnzbd skip_dashboard query parameter.</summary>
            [QueryParameter("skip_dashboard")]
            public int? SkipDashboard { get; set; }
            /// <summary>SABnzbd sort query parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
            /// <summary>SABnzbd sort_cats query parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort_cats")]
            public string? SortCats { get; set; }
#nullable restore
#else
            [QueryParameter("sort_cats")]
            public string SortCats { get; set; }
#endif
            /// <summary>SABnzbd sort_string query parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort_string")]
            public string? SortString { get; set; }
#nullable restore
#else
            [QueryParameter("sort_string")]
            public string SortString { get; set; }
#endif
            /// <summary>SABnzbd sort_type query parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort_type")]
            public string? SortType { get; set; }
#nullable restore
#else
            [QueryParameter("sort_type")]
            public string SortType { get; set; }
#endif
            /// <summary>Index of job to start at</summary>
            [QueryParameter("start")]
            public int? Start { get; set; }
            /// <summary>Only return jobs with the specified status or statuses (separated by a comma) Completed Failed Queued = Waiting for post-processing QuickCheck Verifying Repairing Fetching = Job is downloading extra par2 files Extracting Moving Running = Post-processing script is running</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status")]
            public string? Status { get; set; }
#nullable restore
#else
            [QueryParameter("status")]
            public string Status { get; set; }
#endif
            /// <summary>SABnzbd username query parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("username")]
            public string? Username { get; set; }
#nullable restore
#else
            [QueryParameter("username")]
            public string Username { get; set; }
#endif
            /// <summary>Primary command value, commonly an nzo_id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("value")]
            public string? Value { get; set; }
#nullable restore
#else
            [QueryParameter("value")]
            public string Value { get; set; }
#endif
            /// <summary>Secondary command value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("value2")]
            public string? Value2 { get; set; }
#nullable restore
#else
            [QueryParameter("value2")]
            public string Value2 { get; set; }
#endif
            /// <summary>Tertiary command value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("value3")]
            public string? Value3 { get; set; }
#nullable restore
#else
            [QueryParameter("value3")]
            public string Value3 { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
