// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sabnzbd.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApiCommandResponseHistory : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The day_size property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DaySize { get; set; }
#nullable restore
#else
        public string DaySize { get; set; }
#endif
        /// <summary>The last_history_update property</summary>
        public long? LastHistoryUpdate { get; set; }
        /// <summary>The month_size property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MonthSize { get; set; }
#nullable restore
#else
        public string MonthSize { get; set; }
#endif
        /// <summary>The noofslots property</summary>
        public long? Noofslots { get; set; }
        /// <summary>The ppslots property</summary>
        public long? Ppslots { get; set; }
        /// <summary>The slots property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItem>? Slots { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItem> Slots { get; set; }
#endif
        /// <summary>The total_size property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalSize { get; set; }
#nullable restore
#else
        public string TotalSize { get; set; }
#endif
        /// <summary>The week_size property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WeekSize { get; set; }
#nullable restore
#else
        public string WeekSize { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistory"/> and sets the default values.
        /// </summary>
        public ApiCommandResponseHistory()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistory"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistory CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistory();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "day_size", n => { DaySize = n.GetStringValue(); } },
                { "last_history_update", n => { LastHistoryUpdate = n.GetLongValue(); } },
                { "month_size", n => { MonthSize = n.GetStringValue(); } },
                { "noofslots", n => { Noofslots = n.GetLongValue(); } },
                { "ppslots", n => { Ppslots = n.GetLongValue(); } },
                { "slots", n => { Slots = n.GetCollectionOfObjectValues<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItem>(global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "total_size", n => { TotalSize = n.GetStringValue(); } },
                { "week_size", n => { WeekSize = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("day_size", DaySize);
            writer.WriteLongValue("last_history_update", LastHistoryUpdate);
            writer.WriteStringValue("month_size", MonthSize);
            writer.WriteLongValue("noofslots", Noofslots);
            writer.WriteLongValue("ppslots", Ppslots);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItem>("slots", Slots);
            writer.WriteStringValue("total_size", TotalSize);
            writer.WriteStringValue("week_size", WeekSize);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
