// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sabnzbd.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApiCommandResponseHistorySlotsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The action_line property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActionLine { get; set; }
#nullable restore
#else
        public string ActionLine { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The archive property</summary>
        public bool? Archive { get; set; }
        /// <summary>The bytes property</summary>
        public long? Bytes { get; set; }
        /// <summary>The category property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Category { get; set; }
#nullable restore
#else
        public string Category { get; set; }
#endif
        /// <summary>The completed property</summary>
        public long? Completed { get; set; }
        /// <summary>The downloaded property</summary>
        public long? Downloaded { get; set; }
        /// <summary>The download_time property</summary>
        public long? DownloadTime { get; set; }
        /// <summary>The duplicate_key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DuplicateKey { get; set; }
#nullable restore
#else
        public string DuplicateKey { get; set; }
#endif
        /// <summary>The fail_message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailMessage { get; set; }
#nullable restore
#else
        public string FailMessage { get; set; }
#endif
        /// <summary>The has_rating property</summary>
        public bool? HasRating { get; set; }
        /// <summary>The loaded property</summary>
        public bool? Loaded { get; set; }
        /// <summary>The md5sum property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Md5sum { get; set; }
#nullable restore
#else
        public string Md5sum { get; set; }
#endif
        /// <summary>The meta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItemMeta? Meta { get; set; }
#nullable restore
#else
        public global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItemMeta Meta { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The nzb_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NzbName { get; set; }
#nullable restore
#else
        public string NzbName { get; set; }
#endif
        /// <summary>The nzo_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NzoId { get; set; }
#nullable restore
#else
        public string NzoId { get; set; }
#endif
        /// <summary>The password property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Password { get; set; }
#nullable restore
#else
        public string Password { get; set; }
#endif
        /// <summary>The path property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The postproc_time property</summary>
        public long? PostprocTime { get; set; }
        /// <summary>The pp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pp { get; set; }
#nullable restore
#else
        public string Pp { get; set; }
#endif
        /// <summary>The report property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Report { get; set; }
#nullable restore
#else
        public string Report { get; set; }
#endif
        /// <summary>The retry property</summary>
        public long? Retry { get; set; }
        /// <summary>The script property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Script { get; set; }
#nullable restore
#else
        public string Script { get; set; }
#endif
        /// <summary>The script_line property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScriptLine { get; set; }
#nullable restore
#else
        public string ScriptLine { get; set; }
#endif
        /// <summary>The size property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Size { get; set; }
#nullable restore
#else
        public string Size { get; set; }
#endif
        /// <summary>The stage_log property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItemStageLogItem>? StageLog { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItemStageLogItem> StageLog { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The storage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Storage { get; set; }
#nullable restore
#else
        public string Storage { get; set; }
#endif
        /// <summary>The time_added property</summary>
        public long? TimeAdded { get; set; }
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The url_info property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UrlInfo { get; set; }
#nullable restore
#else
        public string UrlInfo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItem"/> and sets the default values.
        /// </summary>
        public ApiCommandResponseHistorySlotsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action_line", n => { ActionLine = n.GetStringValue(); } },
                { "archive", n => { Archive = n.GetBoolValue(); } },
                { "bytes", n => { Bytes = n.GetLongValue(); } },
                { "category", n => { Category = n.GetStringValue(); } },
                { "completed", n => { Completed = n.GetLongValue(); } },
                { "download_time", n => { DownloadTime = n.GetLongValue(); } },
                { "downloaded", n => { Downloaded = n.GetLongValue(); } },
                { "duplicate_key", n => { DuplicateKey = n.GetStringValue(); } },
                { "fail_message", n => { FailMessage = n.GetStringValue(); } },
                { "has_rating", n => { HasRating = n.GetBoolValue(); } },
                { "loaded", n => { Loaded = n.GetBoolValue(); } },
                { "md5sum", n => { Md5sum = n.GetStringValue(); } },
                { "meta", n => { Meta = n.GetObjectValue<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItemMeta>(global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItemMeta.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "nzb_name", n => { NzbName = n.GetStringValue(); } },
                { "nzo_id", n => { NzoId = n.GetStringValue(); } },
                { "password", n => { Password = n.GetStringValue(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "postproc_time", n => { PostprocTime = n.GetLongValue(); } },
                { "pp", n => { Pp = n.GetStringValue(); } },
                { "report", n => { Report = n.GetStringValue(); } },
                { "retry", n => { Retry = n.GetLongValue(); } },
                { "script", n => { Script = n.GetStringValue(); } },
                { "script_line", n => { ScriptLine = n.GetStringValue(); } },
                { "size", n => { Size = n.GetStringValue(); } },
                { "stage_log", n => { StageLog = n.GetCollectionOfObjectValues<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItemStageLogItem>(global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItemStageLogItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "storage", n => { Storage = n.GetStringValue(); } },
                { "time_added", n => { TimeAdded = n.GetLongValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "url_info", n => { UrlInfo = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("action_line", ActionLine);
            writer.WriteBoolValue("archive", Archive);
            writer.WriteLongValue("bytes", Bytes);
            writer.WriteStringValue("category", Category);
            writer.WriteLongValue("completed", Completed);
            writer.WriteLongValue("downloaded", Downloaded);
            writer.WriteLongValue("download_time", DownloadTime);
            writer.WriteStringValue("duplicate_key", DuplicateKey);
            writer.WriteStringValue("fail_message", FailMessage);
            writer.WriteBoolValue("has_rating", HasRating);
            writer.WriteBoolValue("loaded", Loaded);
            writer.WriteStringValue("md5sum", Md5sum);
            writer.WriteObjectValue<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItemMeta>("meta", Meta);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("nzb_name", NzbName);
            writer.WriteStringValue("nzo_id", NzoId);
            writer.WriteStringValue("password", Password);
            writer.WriteStringValue("path", Path);
            writer.WriteLongValue("postproc_time", PostprocTime);
            writer.WriteStringValue("pp", Pp);
            writer.WriteStringValue("report", Report);
            writer.WriteLongValue("retry", Retry);
            writer.WriteStringValue("script", Script);
            writer.WriteStringValue("script_line", ScriptLine);
            writer.WriteStringValue("size", Size);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistorySlotsItemStageLogItem>("stage_log", StageLog);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("storage", Storage);
            writer.WriteLongValue("time_added", TimeAdded);
            writer.WriteStringValue("url", Url);
            writer.WriteStringValue("url_info", UrlInfo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
