// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sabnzbd.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApiCommandResponseQueueSlotsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The avg_age property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AvgAge { get; set; }
#nullable restore
#else
        public string AvgAge { get; set; }
#endif
        /// <summary>The cat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cat { get; set; }
#nullable restore
#else
        public string Cat { get; set; }
#endif
        /// <summary>The direct_unpack property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DirectUnpack { get; set; }
#nullable restore
#else
        public string DirectUnpack { get; set; }
#endif
        /// <summary>The filename property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Filename { get; set; }
#nullable restore
#else
        public string Filename { get; set; }
#endif
        /// <summary>The index property</summary>
        public long? Index { get; set; }
        /// <summary>The labels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Labels { get; set; }
#nullable restore
#else
        public List<string> Labels { get; set; }
#endif
        /// <summary>The mb property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mb { get; set; }
#nullable restore
#else
        public string Mb { get; set; }
#endif
        /// <summary>The mbleft property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mbleft { get; set; }
#nullable restore
#else
        public string Mbleft { get; set; }
#endif
        /// <summary>The mbmissing property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mbmissing { get; set; }
#nullable restore
#else
        public string Mbmissing { get; set; }
#endif
        /// <summary>The nzo_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NzoId { get; set; }
#nullable restore
#else
        public string NzoId { get; set; }
#endif
        /// <summary>The password property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Password { get; set; }
#nullable restore
#else
        public string Password { get; set; }
#endif
        /// <summary>The percentage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Percentage { get; set; }
#nullable restore
#else
        public string Percentage { get; set; }
#endif
        /// <summary>The priority property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Priority { get; set; }
#nullable restore
#else
        public string Priority { get; set; }
#endif
        /// <summary>The script property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Script { get; set; }
#nullable restore
#else
        public string Script { get; set; }
#endif
        /// <summary>The size property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Size { get; set; }
#nullable restore
#else
        public string Size { get; set; }
#endif
        /// <summary>The sizeleft property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sizeleft { get; set; }
#nullable restore
#else
        public string Sizeleft { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The time_added property</summary>
        public long? TimeAdded { get; set; }
        /// <summary>The timeleft property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timeleft { get; set; }
#nullable restore
#else
        public string Timeleft { get; set; }
#endif
        /// <summary>The unpackopts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Unpackopts { get; set; }
#nullable restore
#else
        public string Unpackopts { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueueSlotsItem"/> and sets the default values.
        /// </summary>
        public ApiCommandResponseQueueSlotsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueueSlotsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueueSlotsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueueSlotsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "avg_age", n => { AvgAge = n.GetStringValue(); } },
                { "cat", n => { Cat = n.GetStringValue(); } },
                { "direct_unpack", n => { DirectUnpack = n.GetStringValue(); } },
                { "filename", n => { Filename = n.GetStringValue(); } },
                { "index", n => { Index = n.GetLongValue(); } },
                { "labels", n => { Labels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "mb", n => { Mb = n.GetStringValue(); } },
                { "mbleft", n => { Mbleft = n.GetStringValue(); } },
                { "mbmissing", n => { Mbmissing = n.GetStringValue(); } },
                { "nzo_id", n => { NzoId = n.GetStringValue(); } },
                { "password", n => { Password = n.GetStringValue(); } },
                { "percentage", n => { Percentage = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetStringValue(); } },
                { "script", n => { Script = n.GetStringValue(); } },
                { "size", n => { Size = n.GetStringValue(); } },
                { "sizeleft", n => { Sizeleft = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "time_added", n => { TimeAdded = n.GetLongValue(); } },
                { "timeleft", n => { Timeleft = n.GetStringValue(); } },
                { "unpackopts", n => { Unpackopts = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("avg_age", AvgAge);
            writer.WriteStringValue("cat", Cat);
            writer.WriteStringValue("direct_unpack", DirectUnpack);
            writer.WriteStringValue("filename", Filename);
            writer.WriteLongValue("index", Index);
            writer.WriteCollectionOfPrimitiveValues<string>("labels", Labels);
            writer.WriteStringValue("mb", Mb);
            writer.WriteStringValue("mbleft", Mbleft);
            writer.WriteStringValue("mbmissing", Mbmissing);
            writer.WriteStringValue("nzo_id", NzoId);
            writer.WriteStringValue("password", Password);
            writer.WriteStringValue("percentage", Percentage);
            writer.WriteStringValue("priority", Priority);
            writer.WriteStringValue("script", Script);
            writer.WriteStringValue("size", Size);
            writer.WriteStringValue("sizeleft", Sizeleft);
            writer.WriteStringValue("status", Status);
            writer.WriteLongValue("time_added", TimeAdded);
            writer.WriteStringValue("timeleft", Timeleft);
            writer.WriteStringValue("unpackopts", Unpackopts);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
