// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sabnzbd.OpenApiClient.Models
{
    /// <summary>
    /// Combined response envelope inferred from the JSON examples in the SABnzbd API reference. Only properties returned by the selected command are populated.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiCommandResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The categories property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Categories { get; set; }
#nullable restore
#else
        public List<string> Categories { get; set; }
#endif
        /// <summary>The day property</summary>
        public long? Day { get; set; }
        /// <summary>The files property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseFilesItem>? Files { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseFilesItem> Files { get; set; }
#endif
        /// <summary>The history property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistory? History { get; set; }
#nullable restore
#else
        public global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistory History { get; set; }
#endif
        /// <summary>The month property</summary>
        public long? Month { get; set; }
        /// <summary>The nzo_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? NzoIds { get; set; }
#nullable restore
#else
        public List<string> NzoIds { get; set; }
#endif
        /// <summary>The position property</summary>
        public long? Position { get; set; }
        /// <summary>The queue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueue? Queue { get; set; }
#nullable restore
#else
        public global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueue Queue { get; set; }
#endif
        /// <summary>The result property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseResult? Result { get; set; }
#nullable restore
#else
        public global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseResult Result { get; set; }
#endif
        /// <summary>The scripts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Scripts { get; set; }
#nullable restore
#else
        public List<string> Scripts { get; set; }
#endif
        /// <summary>The servers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseServersProperty? Servers { get; set; }
#nullable restore
#else
        public global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseServersProperty Servers { get; set; }
#endif
        /// <summary>The status property</summary>
        public bool? Status { get; set; }
        /// <summary>The total property</summary>
        public long? Total { get; set; }
        /// <summary>The value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseValue? Value { get; set; }
#nullable restore
#else
        public global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseValue Value { get; set; }
#endif
        /// <summary>The warnings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseWarningsItem>? Warnings { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseWarningsItem> Warnings { get; set; }
#endif
        /// <summary>The week property</summary>
        public long? Week { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponse"/> and sets the default values.
        /// </summary>
        public ApiCommandResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "categories", n => { Categories = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "day", n => { Day = n.GetLongValue(); } },
                { "files", n => { Files = n.GetCollectionOfObjectValues<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseFilesItem>(global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseFilesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "history", n => { History = n.GetObjectValue<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistory>(global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistory.CreateFromDiscriminatorValue); } },
                { "month", n => { Month = n.GetLongValue(); } },
                { "nzo_ids", n => { NzoIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "position", n => { Position = n.GetLongValue(); } },
                { "queue", n => { Queue = n.GetObjectValue<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueue>(global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueue.CreateFromDiscriminatorValue); } },
                { "result", n => { Result = n.GetObjectValue<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseResult>(global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseResult.CreateFromDiscriminatorValue); } },
                { "scripts", n => { Scripts = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "servers", n => { Servers = n.GetObjectValue<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseServersProperty>(global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseServersProperty.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetBoolValue(); } },
                { "total", n => { Total = n.GetLongValue(); } },
                { "value", n => { Value = n.GetObjectValue<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseValue>(global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseValue.CreateFromDiscriminatorValue); } },
                { "warnings", n => { Warnings = n.GetCollectionOfObjectValues<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseWarningsItem>(global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseWarningsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "week", n => { Week = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("categories", Categories);
            writer.WriteLongValue("day", Day);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseFilesItem>("files", Files);
            writer.WriteObjectValue<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseHistory>("history", History);
            writer.WriteLongValue("month", Month);
            writer.WriteCollectionOfPrimitiveValues<string>("nzo_ids", NzoIds);
            writer.WriteLongValue("position", Position);
            writer.WriteObjectValue<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueue>("queue", Queue);
            writer.WriteObjectValue<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseResult>("result", Result);
            writer.WriteCollectionOfPrimitiveValues<string>("scripts", Scripts);
            writer.WriteObjectValue<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseServersProperty>("servers", Servers);
            writer.WriteBoolValue("status", Status);
            writer.WriteLongValue("total", Total);
            writer.WriteObjectValue<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseValue>("value", Value);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseWarningsItem>("warnings", Warnings);
            writer.WriteLongValue("week", Week);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
