// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Sabnzbd.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApiCommandResponseQueue : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cache_art property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CacheArt { get; set; }
#nullable restore
#else
        public string CacheArt { get; set; }
#endif
        /// <summary>The cache_size property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CacheSize { get; set; }
#nullable restore
#else
        public string CacheSize { get; set; }
#endif
        /// <summary>The diskspace1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Diskspace1 { get; set; }
#nullable restore
#else
        public string Diskspace1 { get; set; }
#endif
        /// <summary>The diskspace1_norm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Diskspace1Norm { get; set; }
#nullable restore
#else
        public string Diskspace1Norm { get; set; }
#endif
        /// <summary>The diskspace2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Diskspace2 { get; set; }
#nullable restore
#else
        public string Diskspace2 { get; set; }
#endif
        /// <summary>The diskspace2_norm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Diskspace2Norm { get; set; }
#nullable restore
#else
        public string Diskspace2Norm { get; set; }
#endif
        /// <summary>The diskspacetotal1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Diskspacetotal1 { get; set; }
#nullable restore
#else
        public string Diskspacetotal1 { get; set; }
#endif
        /// <summary>The diskspacetotal2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Diskspacetotal2 { get; set; }
#nullable restore
#else
        public string Diskspacetotal2 { get; set; }
#endif
        /// <summary>The finish property</summary>
        public long? Finish { get; set; }
        /// <summary>The finishaction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueueFinishaction? Finishaction { get; set; }
#nullable restore
#else
        public global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueueFinishaction Finishaction { get; set; }
#endif
        /// <summary>The have_quota property</summary>
        public bool? HaveQuota { get; set; }
        /// <summary>The have_warnings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HaveWarnings { get; set; }
#nullable restore
#else
        public string HaveWarnings { get; set; }
#endif
        /// <summary>The kbpersec property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Kbpersec { get; set; }
#nullable restore
#else
        public string Kbpersec { get; set; }
#endif
        /// <summary>The left_quota property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeftQuota { get; set; }
#nullable restore
#else
        public string LeftQuota { get; set; }
#endif
        /// <summary>The limit property</summary>
        public long? Limit { get; set; }
        /// <summary>The mb property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mb { get; set; }
#nullable restore
#else
        public string Mb { get; set; }
#endif
        /// <summary>The mbleft property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mbleft { get; set; }
#nullable restore
#else
        public string Mbleft { get; set; }
#endif
        /// <summary>The noofslots property</summary>
        public long? Noofslots { get; set; }
        /// <summary>The noofslots_total property</summary>
        public long? NoofslotsTotal { get; set; }
        /// <summary>The paused property</summary>
        public bool? Paused { get; set; }
        /// <summary>The paused_all property</summary>
        public bool? PausedAll { get; set; }
        /// <summary>The pause_int property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PauseInt { get; set; }
#nullable restore
#else
        public string PauseInt { get; set; }
#endif
        /// <summary>The quota property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Quota { get; set; }
#nullable restore
#else
        public string Quota { get; set; }
#endif
        /// <summary>The size property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Size { get; set; }
#nullable restore
#else
        public string Size { get; set; }
#endif
        /// <summary>The sizeleft property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sizeleft { get; set; }
#nullable restore
#else
        public string Sizeleft { get; set; }
#endif
        /// <summary>The slots property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueueSlotsItem>? Slots { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueueSlotsItem> Slots { get; set; }
#endif
        /// <summary>The speed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Speed { get; set; }
#nullable restore
#else
        public string Speed { get; set; }
#endif
        /// <summary>The speedlimit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Speedlimit { get; set; }
#nullable restore
#else
        public string Speedlimit { get; set; }
#endif
        /// <summary>The speedlimit_abs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpeedlimitAbs { get; set; }
#nullable restore
#else
        public string SpeedlimitAbs { get; set; }
#endif
        /// <summary>The start property</summary>
        public long? Start { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The timeleft property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timeleft { get; set; }
#nullable restore
#else
        public string Timeleft { get; set; }
#endif
        /// <summary>The version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueue"/> and sets the default values.
        /// </summary>
        public ApiCommandResponseQueue()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueue();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cache_art", n => { CacheArt = n.GetStringValue(); } },
                { "cache_size", n => { CacheSize = n.GetStringValue(); } },
                { "diskspace1", n => { Diskspace1 = n.GetStringValue(); } },
                { "diskspace1_norm", n => { Diskspace1Norm = n.GetStringValue(); } },
                { "diskspace2", n => { Diskspace2 = n.GetStringValue(); } },
                { "diskspace2_norm", n => { Diskspace2Norm = n.GetStringValue(); } },
                { "diskspacetotal1", n => { Diskspacetotal1 = n.GetStringValue(); } },
                { "diskspacetotal2", n => { Diskspacetotal2 = n.GetStringValue(); } },
                { "finish", n => { Finish = n.GetLongValue(); } },
                { "finishaction", n => { Finishaction = n.GetObjectValue<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueueFinishaction>(global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueueFinishaction.CreateFromDiscriminatorValue); } },
                { "have_quota", n => { HaveQuota = n.GetBoolValue(); } },
                { "have_warnings", n => { HaveWarnings = n.GetStringValue(); } },
                { "kbpersec", n => { Kbpersec = n.GetStringValue(); } },
                { "left_quota", n => { LeftQuota = n.GetStringValue(); } },
                { "limit", n => { Limit = n.GetLongValue(); } },
                { "mb", n => { Mb = n.GetStringValue(); } },
                { "mbleft", n => { Mbleft = n.GetStringValue(); } },
                { "noofslots", n => { Noofslots = n.GetLongValue(); } },
                { "noofslots_total", n => { NoofslotsTotal = n.GetLongValue(); } },
                { "pause_int", n => { PauseInt = n.GetStringValue(); } },
                { "paused", n => { Paused = n.GetBoolValue(); } },
                { "paused_all", n => { PausedAll = n.GetBoolValue(); } },
                { "quota", n => { Quota = n.GetStringValue(); } },
                { "size", n => { Size = n.GetStringValue(); } },
                { "sizeleft", n => { Sizeleft = n.GetStringValue(); } },
                { "slots", n => { Slots = n.GetCollectionOfObjectValues<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueueSlotsItem>(global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueueSlotsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "speed", n => { Speed = n.GetStringValue(); } },
                { "speedlimit", n => { Speedlimit = n.GetStringValue(); } },
                { "speedlimit_abs", n => { SpeedlimitAbs = n.GetStringValue(); } },
                { "start", n => { Start = n.GetLongValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "timeleft", n => { Timeleft = n.GetStringValue(); } },
                { "version", n => { Version = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cache_art", CacheArt);
            writer.WriteStringValue("cache_size", CacheSize);
            writer.WriteStringValue("diskspace1", Diskspace1);
            writer.WriteStringValue("diskspace1_norm", Diskspace1Norm);
            writer.WriteStringValue("diskspace2", Diskspace2);
            writer.WriteStringValue("diskspace2_norm", Diskspace2Norm);
            writer.WriteStringValue("diskspacetotal1", Diskspacetotal1);
            writer.WriteStringValue("diskspacetotal2", Diskspacetotal2);
            writer.WriteLongValue("finish", Finish);
            writer.WriteObjectValue<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueueFinishaction>("finishaction", Finishaction);
            writer.WriteBoolValue("have_quota", HaveQuota);
            writer.WriteStringValue("have_warnings", HaveWarnings);
            writer.WriteStringValue("kbpersec", Kbpersec);
            writer.WriteStringValue("left_quota", LeftQuota);
            writer.WriteLongValue("limit", Limit);
            writer.WriteStringValue("mb", Mb);
            writer.WriteStringValue("mbleft", Mbleft);
            writer.WriteLongValue("noofslots", Noofslots);
            writer.WriteLongValue("noofslots_total", NoofslotsTotal);
            writer.WriteBoolValue("paused", Paused);
            writer.WriteBoolValue("paused_all", PausedAll);
            writer.WriteStringValue("pause_int", PauseInt);
            writer.WriteStringValue("quota", Quota);
            writer.WriteStringValue("size", Size);
            writer.WriteStringValue("sizeleft", Sizeleft);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Sabnzbd.OpenApiClient.Models.ApiCommandResponseQueueSlotsItem>("slots", Slots);
            writer.WriteStringValue("speed", Speed);
            writer.WriteStringValue("speedlimit", Speedlimit);
            writer.WriteStringValue("speedlimit_abs", SpeedlimitAbs);
            writer.WriteLongValue("start", Start);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("timeleft", Timeleft);
            writer.WriteStringValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
