// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sabnzbd.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Mode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "addlocalfile")]
        #pragma warning disable CS1591
        Addlocalfile,
        #pragma warning restore CS1591
        [EnumMember(Value = "addurl")]
        #pragma warning disable CS1591
        Addurl,
        #pragma warning restore CS1591
        [EnumMember(Value = "auth")]
        #pragma warning disable CS1591
        Auth,
        #pragma warning restore CS1591
        [EnumMember(Value = "cancel_pp")]
        #pragma warning disable CS1591
        CancelPp,
        #pragma warning restore CS1591
        [EnumMember(Value = "change_cat")]
        #pragma warning disable CS1591
        ChangeCat,
        #pragma warning restore CS1591
        [EnumMember(Value = "change_opts")]
        #pragma warning disable CS1591
        ChangeOpts,
        #pragma warning restore CS1591
        [EnumMember(Value = "change_script")]
        #pragma warning disable CS1591
        ChangeScript,
        #pragma warning restore CS1591
        [EnumMember(Value = "config")]
        #pragma warning disable CS1591
        Config,
        #pragma warning restore CS1591
        [EnumMember(Value = "del_config")]
        #pragma warning disable CS1591
        DelConfig,
        #pragma warning restore CS1591
        [EnumMember(Value = "disconnect")]
        #pragma warning disable CS1591
        Disconnect,
        #pragma warning restore CS1591
        [EnumMember(Value = "fullstatus")]
        #pragma warning disable CS1591
        Fullstatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "get_cats")]
        #pragma warning disable CS1591
        GetCats,
        #pragma warning restore CS1591
        [EnumMember(Value = "get_config")]
        #pragma warning disable CS1591
        GetConfig,
        #pragma warning restore CS1591
        [EnumMember(Value = "get_files")]
        #pragma warning disable CS1591
        GetFiles,
        #pragma warning restore CS1591
        [EnumMember(Value = "get_scripts")]
        #pragma warning disable CS1591
        GetScripts,
        #pragma warning restore CS1591
        [EnumMember(Value = "history")]
        #pragma warning disable CS1591
        History,
        #pragma warning restore CS1591
        [EnumMember(Value = "move_nzf_bulk")]
        #pragma warning disable CS1591
        MoveNzfBulk,
        #pragma warning restore CS1591
        [EnumMember(Value = "pause")]
        #pragma warning disable CS1591
        Pause,
        #pragma warning restore CS1591
        [EnumMember(Value = "pause_pp")]
        #pragma warning disable CS1591
        PausePp,
        #pragma warning restore CS1591
        [EnumMember(Value = "queue")]
        #pragma warning disable CS1591
        Queue,
        #pragma warning restore CS1591
        [EnumMember(Value = "reset_quota")]
        #pragma warning disable CS1591
        ResetQuota,
        #pragma warning restore CS1591
        [EnumMember(Value = "restart")]
        #pragma warning disable CS1591
        Restart,
        #pragma warning restore CS1591
        [EnumMember(Value = "restart_repair")]
        #pragma warning disable CS1591
        RestartRepair,
        #pragma warning restore CS1591
        [EnumMember(Value = "resume")]
        #pragma warning disable CS1591
        Resume,
        #pragma warning restore CS1591
        [EnumMember(Value = "resume_pp")]
        #pragma warning disable CS1591
        ResumePp,
        #pragma warning restore CS1591
        [EnumMember(Value = "retry")]
        #pragma warning disable CS1591
        Retry,
        #pragma warning restore CS1591
        [EnumMember(Value = "retry_all")]
        #pragma warning disable CS1591
        RetryAll,
        #pragma warning restore CS1591
        [EnumMember(Value = "rss_now")]
        #pragma warning disable CS1591
        RssNow,
        #pragma warning restore CS1591
        [EnumMember(Value = "server_stats")]
        #pragma warning disable CS1591
        ServerStats,
        #pragma warning restore CS1591
        [EnumMember(Value = "set_config")]
        #pragma warning disable CS1591
        SetConfig,
        #pragma warning restore CS1591
        [EnumMember(Value = "set_config_default")]
        #pragma warning disable CS1591
        SetConfigDefault,
        #pragma warning restore CS1591
        [EnumMember(Value = "showlog")]
        #pragma warning disable CS1591
        Showlog,
        #pragma warning restore CS1591
        [EnumMember(Value = "shutdown")]
        #pragma warning disable CS1591
        Shutdown,
        #pragma warning restore CS1591
        [EnumMember(Value = "status")]
        #pragma warning disable CS1591
        Status,
        #pragma warning restore CS1591
        [EnumMember(Value = "switch")]
        #pragma warning disable CS1591
        SwitchValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "translate")]
        #pragma warning disable CS1591
        Translate,
        #pragma warning restore CS1591
        [EnumMember(Value = "version")]
        #pragma warning disable CS1591
        Version,
        #pragma warning restore CS1591
        [EnumMember(Value = "warnings")]
        #pragma warning disable CS1591
        Warnings,
        #pragma warning restore CS1591
        [EnumMember(Value = "watched_now")]
        #pragma warning disable CS1591
        WatchedNow,
        #pragma warning restore CS1591
    }
}
