// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Sabnzbd.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum NzbUploadRequestMode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "addfile")]
        #pragma warning disable CS1591
        Addfile,
        #pragma warning restore CS1591
        [EnumMember(Value = "retry")]
        #pragma warning disable CS1591
        Retry,
        #pragma warning restore CS1591
    }
}
